/**
 * One narrated insight, in the five sections the backend produced.
 *
 * The card renders prose it did not write and a confidence figure it did not
 * compute. Two things it adds, both about provenance rather than content:
 *
 * **Where the words came from.** A `TEMPLATE` badge is not an apology — a
 * rejected generation means a validator caught something, and the reader is
 * entitled to know which. The failing validators are shown, not hidden.
 *
 * **What kind of claim this is.** T3 is an association; the tier chip says so
 * next to the confidence figure, because a percentage beside a sentence reads
 * as certainty about the sentence unless it is told otherwise.
 */

import type { Narration } from '../api/types';
import { RejectedGeneration } from './RejectedGeneration';

const TIER_LABEL: Record<string, string> = {
  T1: 'Measured',
  T2: 'Compared',
  T3: 'Association',
};

const TIER_HINT: Record<string, string> = {
  T1: 'Exact arithmetic over what you recorded',
  T2: 'A comparison of two complete periods',
  T3: 'A statistical association, not a cause',
};

export function InsightCard({ narration }: { narration: Narration }) {
  const { tier, source, confidence_value: confidence } = narration;
  const isTemplate = source === 'TEMPLATE';

  return (
    <article className="card insight" aria-label={narration.observation}>
      <div className="insight__top">
        <span className="chip chip--neutral" title={TIER_HINT[tier]}>
          <span className="chip__dot" aria-hidden="true" />
          {TIER_LABEL[tier] ?? tier}
        </span>
        <span className="card__hint">
          {isTemplate ? 'Written from a template' : `Generated by ${narration.model}`}
        </span>
      </div>

      <h3 className="insight__observation">{narration.observation}</h3>

      <div className="insight__section">
        <p className="insight__section-label">Evidence</p>
        <p className="insight__section-body">{narration.evidence}</p>
      </div>

      <div className="insight__section">
        <p className="insight__section-label">Interpretation</p>
        <p className="insight__section-body">{narration.interpretation}</p>
      </div>

      {narration.suggestion ? (
        <p className="insight__suggestion">
          <span className="visually-hidden">Suggestion: </span>
          {narration.suggestion}
        </p>
      ) : null}

      <div className="insight__confidence">
        {confidence !== null ? (
          <div
            className="confidence-meter"
            role="meter"
            aria-valuenow={Math.round(confidence * 100)}
            aria-valuemin={0}
            aria-valuemax={100}
            aria-label="Confidence"
          >
            <div className="confidence-meter__fill" style={{ width: `${confidence * 100}%` }} />
          </div>
        ) : null}
        <p className="insight__confidence-text">{narration.confidence}</p>
      </div>

      <RejectedGeneration failures={narration.validation_failures} />
    </article>
  );
}
